name: gif comment
on:
  issues:
    types: [opened]
jobs:
  comment:
    if: github.event_name == 'issues'
    runs-on: ubuntu-latest
    steps:
      - name: Add gif comment
        uses: Marta83/funny-comment-action@v2
        id: FunnyComment
        with:
          GIPHY_TOKEN: ${{ secrets.GIPHY_TOKEN }}
          comment_type: 'gif'
